function B = BFunc(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,dq1,dq2,dq3,q2,q3)
%BFUNC
%    B = BFUNC(IXX,IXY,IXZ,IYY,IYZ,IZZ,DQ1,DQ2,DQ3,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Jul-2018 11:39:04

t2 = dq2.^2;
t3 = cos(q2);
t4 = cos(q3);
t5 = dq3.^2;
t6 = sin(q3);
t7 = sin(q2);
t8 = q2.*2.0;
t9 = sin(t8);
t10 = t3.^2;
t11 = t4.^2;
t12 = dq1.^2;
t13 = q3.*2.0;
t14 = sin(t13);
B = [-Iyz.*t2.*t7+Ixy.*t2.*t3.*t4-Ixy.*t3.*t4.*t5-Ixz.*t2.*t3.*t6+Ixz.*t3.*t5.*t6+Iyz.*t2.*t7.*t11.*2.0-Ixx.*dq2.*dq3.*t3+Ixx.*dq1.*dq2.*t9-Ixy.*dq1.*dq2.*t6.*2.0-Ixz.*dq1.*dq2.*t4.*2.0-Iyy.*dq2.*dq3.*t3-Iyy.*dq1.*dq2.*t9+Iyz.*dq1.*dq3.*t10.*2.0+Izz.*dq2.*dq3.*t3+Ixy.*dq1.*dq2.*t6.*t10.*4.0+Ixz.*dq1.*dq2.*t4.*t10.*4.0+Iyy.*dq2.*dq3.*t3.*t11.*2.0-Iyz.*dq1.*dq3.*t10.*t11.*4.0-Izz.*dq2.*dq3.*t3.*t11.*2.0-Iyy.*t2.*t4.*t6.*t7+Izz.*t2.*t4.*t6.*t7+Ixy.*dq1.*dq3.*t3.*t4.*t7.*2.0-Ixz.*dq1.*dq3.*t3.*t6.*t7.*2.0+Iyy.*dq1.*dq2.*t3.*t7.*t11.*2.0+Iyy.*dq1.*dq3.*t4.*t6.*t10.*2.0+Iyz.*dq2.*dq3.*t3.*t4.*t6.*4.0-Izz.*dq1.*dq2.*t3.*t7.*t11.*2.0-Izz.*dq1.*dq3.*t4.*t6.*t10.*2.0+Iyz.*dq1.*dq2.*t3.*t4.*t6.*t7.*4.0;Iyz.*dq2.*dq3.*-2.0-Ixx.*t9.*t12.*(1.0./2.0)+Ixy.*t5.*t6+Ixy.*t6.*t12+Ixz.*t4.*t5+Ixz.*t4.*t12+Iyy.*t9.*t12.*(1.0./2.0)-Ixy.*t6.*t10.*t12.*2.0-Ixz.*t4.*t10.*t12.*2.0+Ixx.*dq1.*dq3.*t3-Iyy.*dq1.*dq3.*t3-Iyy.*dq2.*dq3.*t14+Iyz.*dq2.*dq3.*t11.*4.0+Izz.*dq1.*dq3.*t3+Izz.*dq2.*dq3.*t14-Ixy.*dq1.*dq3.*t6.*t7.*2.0-Ixz.*dq1.*dq3.*t4.*t7.*2.0+Iyy.*dq1.*dq3.*t3.*t11.*2.0-Izz.*dq1.*dq3.*t3.*t11.*2.0-Iyy.*t3.*t7.*t11.*t12+Izz.*t3.*t7.*t11.*t12+Iyz.*dq1.*dq3.*t3.*t4.*t6.*4.0-Iyz.*t3.*t4.*t6.*t7.*t12.*2.0;Iyz.*t2+Iyy.*t2.*t14.*(1.0./2.0)-Iyz.*t2.*t11.*2.0-Iyz.*t10.*t12-Izz.*t2.*t14.*(1.0./2.0)+Iyz.*t10.*t11.*t12.*2.0-Ixx.*dq1.*dq2.*t3+Iyy.*dq1.*dq2.*t3-Izz.*dq1.*dq2.*t3+Ixy.*dq1.*dq2.*t6.*t7.*2.0+Ixz.*dq1.*dq2.*t4.*t7.*2.0-Iyy.*dq1.*dq2.*t3.*t11.*2.0+Izz.*dq1.*dq2.*t3.*t11.*2.0-Ixy.*t3.*t4.*t7.*t12+Ixz.*t3.*t6.*t7.*t12-Iyy.*t4.*t6.*t10.*t12+Izz.*t4.*t6.*t10.*t12-Iyz.*dq1.*dq2.*t3.*t4.*t6.*4.0];
