function H_global = HFunc(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,dq1,dq2,dq3,q1,q2,q3)
%HFUNC
%    H_GLOBAL = HFUNC(IXX,IXY,IXZ,IYY,IYZ,IZZ,DQ1,DQ2,DQ3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Jul-2018 11:39:05

t2 = conj(q1);
t3 = conj(q3);
t4 = sin(q3);
t5 = cos(q2);
t6 = cos(q3);
t7 = sin(t2);
t8 = sin(t3);
t9 = cos(t2);
t10 = cos(t3);
t11 = conj(q2);
t12 = sin(t11);
t13 = sin(q2);
t20 = dq1.*t13;
t14 = dq3-t20;
t15 = dq2.*t6;
t16 = dq1.*t4.*t5;
t17 = t15+t16;
t18 = dq2.*t4;
t21 = dq1.*t5.*t6;
t19 = t18-t21;
t22 = Iyy.*t17;
t23 = Iyz.*t19;
t34 = Ixy.*t14;
t24 = t22+t23-t34;
t25 = Ixz.*t14;
t26 = Iyz.*t17;
t27 = Izz.*t19;
t28 = t25+t26+t27;
t29 = cos(t11);
t30 = Ixx.*t14;
t31 = Ixz.*t19;
t33 = Ixy.*t17;
t32 = t30+t31-t33;
H_global = [-t24.*(t7.*t10-t8.*t9.*t12)-t28.*(t7.*t8+t9.*t10.*t12)+t9.*t29.*t32;t24.*(t9.*t10+t7.*t8.*t12)+t28.*(t8.*t9-t7.*t10.*t12)+t7.*t29.*t32;-t12.*t32+t8.*t24.*t29-t10.*t28.*t29];
