function M = MFunc(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,q2,q3)
%MFUNC
%    M = MFUNC(IXX,IXY,IXZ,IYY,IYZ,IZZ,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Jul-2018 11:39:04

t2 = sin(q2);
t3 = cos(q2);
t4 = cos(q3);
t5 = t3.^2;
t6 = sin(q3);
t7 = t4.^2;
t8 = Iyz.*t3;
t9 = Ixy.*t2.*t4;
t10 = Iyy.*t3.*t4.*t6;
t11 = t8+t9+t10-Ixz.*t2.*t6-Iyz.*t3.*t7.*2.0-Izz.*t3.*t4.*t6;
t12 = t6.^2;
t13 = -Ixx.*t2-Ixy.*t3.*t6-Ixz.*t3.*t4;
t14 = Ixz.*t6;
t15 = t14-Ixy.*t4;
M = reshape([Ixx.*t2.^2+Iyy.*t5.*t12+Izz.*t5.*t7+Ixy.*t2.*t3.*t6.*2.0+Ixz.*t2.*t3.*t4.*2.0-Iyz.*t4.*t5.*t6.*2.0,t11,t13,t11,Iyy.*t7+Izz.*t12+Iyz.*t4.*t6.*2.0,t15,t13,t15,Ixx],[3,3]);
