function M_Q = MFunc_Q(Ixx,Ixy,Ixz,Iyy,Iyz,Izz,e0,e1,e2,e3)
%MFUNC_Q
%    M_Q = MFUNC_Q(IXX,IXY,IXZ,IYY,IYZ,IZZ,E0,E1,E2,E3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Jul-2018 10:58:06

t2 = e2.^2;
t3 = e3.^2;
t4 = e1.^2;
t5 = Iyz.*t2.*4.0;
t6 = Ixy.*e0.*e2.*4.0;
t7 = Ixz.*e0.*e3.*4.0;
t8 = Ixz.*e1.*e2.*4.0;
t9 = Iyy.*e2.*e3.*4.0;
t25 = Ixy.*e1.*e3.*4.0;
t10 = t5+t6+t7+t8+t9-t25-Iyz.*t3.*4.0-Ixx.*e0.*e1.*4.0-Izz.*e2.*e3.*4.0;
t11 = e0.^2;
t12 = Ixz.*e0.*e1.*4.0;
t13 = Iyz.*e0.*e2.*4.0;
t14 = Iyz.*e1.*e3.*4.0;
t15 = Ixy.*e0.*e1.*4.0;
t16 = Ixy.*e2.*e3.*4.0;
t17 = Iyz.*e0.*e3.*4.0;
t18 = Ixz.*t3.*4.0;
t19 = Izz.*e1.*e3.*4.0;
t30 = Iyz.*e1.*e2.*4.0;
t20 = t15+t16+t17+t18+t19-t30-Ixz.*t4.*4.0-Ixx.*e1.*e3.*4.0-Iyy.*e0.*e2.*4.0;
t21 = Ixy.*t3.*4.0;
t22 = Ixx.*e0.*e3.*4.0;
t28 = Ixz.*e2.*e3.*4.0;
t23 = t12-t13-t14+t21+t22-t28-Ixy.*t11.*4.0-Iyy.*e0.*e3.*4.0-Izz.*e1.*e2.*4.0;
t24 = Ixy.*e0.*e3.*8.0;
t26 = Ixy.*t4.*4.0;
t27 = Ixx.*e1.*e2.*4.0;
t29 = Ixz.*t2.*4.0;
t31 = Izz.*e0.*e2.*4.0;
t32 = Iyz.*t4.*4.0;
t33 = Iyy.*e0.*e1.*4.0;
t34 = t6-t7-t8-t25+t32+t33-Iyz.*t11.*4.0-Ixx.*e2.*e3.*4.0-Izz.*e0.*e1.*4.0;
t35 = Iyz.*e0.*e1.*8.0;
M_Q = reshape([Ixx.*t4.*4.0+Iyy.*t2.*4.0+Izz.*t3.*4.0-Ixy.*e1.*e2.*8.0-Ixz.*e1.*e3.*8.0-Iyz.*e2.*e3.*8.0,t10,t20,t12+t13+t14+t26+t27-t28-Ixy.*t2.*4.0-Iyy.*e1.*e2.*4.0-Izz.*e0.*e3.*4.0,t10,t24+Ixx.*t11.*4.0+Iyy.*t3.*4.0+Izz.*t2.*4.0-Ixz.*e0.*e2.*8.0+Iyz.*e2.*e3.*8.0,t23,-t15-t16+t17+t29-t30+t31-Ixz.*t11.*4.0-Ixx.*e0.*e2.*4.0-Iyy.*e1.*e3.*4.0,t20,t23,-t24+t35+Ixx.*t3.*4.0+Iyy.*t11.*4.0+Izz.*t4.*4.0+Ixz.*e1.*e3.*8.0,t34,t12+t13+t14+t26+t27-Ixy.*t2.*4.0-Ixz.*e2.*e3.*4.0-Iyy.*e1.*e2.*4.0-Izz.*e0.*e3.*4.0,-t15-t16+t17+t29+t31-Ixz.*t11.*4.0-Ixx.*e0.*e2.*4.0-Iyy.*e1.*e3.*4.0-Iyz.*e1.*e2.*4.0,t34,-t35+Ixx.*t2.*4.0+Iyy.*t4.*4.0+Izz.*t11.*4.0+Ixy.*e1.*e2.*8.0+Ixz.*e0.*e2.*8.0],[4,4]);
